version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: CarRental_db
      MYSQL_ROOT_PASSWORD: root_2112
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1" ]
      interval: 10s
      timeout: 2s
      retries: 10
  #  app:
  #    depends_on:
  #      - db
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ADS_Lab6
  #version: '3.1'
  #services:
  #  db:
  #    image: mysql
  #    restart: always
  #    environment:
  #      MYSQL_DATABASE: ADS_Lab6
  #      MYSQL_ROOT_PASSWORD: root_2112
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/CarRental_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_2112
