version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: AdvantisDentalSurgeries
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
  app:
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/AdvantisDentalSurgeries
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root1234
